// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA14Hwgst4p_7_3TjW2eJN2BbwhZZI2_2Q',
    appId: '1:19391297851:web:73e12c2a9d1e4781155f1e',
    messagingSenderId: '19391297851',
    projectId: 'random-chat-app-b',
    authDomain: 'random-chat-app-b.firebaseapp.com',
    storageBucket: 'random-chat-app-b.appspot.com',
    measurementId: 'G-NP1LPDZ0BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7VNmCt0tobF7gx8XzHCLCKuvY0r-_d-c',
    appId: '1:19391297851:android:6f135d92c1ccf752155f1e',
    messagingSenderId: '19391297851',
    projectId: 'random-chat-app-b',
    storageBucket: 'random-chat-app-b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIdASJQAZ09xrHnxZD9C82K2mH1A-f8io',
    appId: '1:19391297851:ios:4c20162f9108b896155f1e',
    messagingSenderId: '19391297851',
    projectId: 'random-chat-app-b',
    storageBucket: 'random-chat-app-b.appspot.com',
    iosBundleId: 'com.example.randamChatAppb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIdASJQAZ09xrHnxZD9C82K2mH1A-f8io',
    appId: '1:19391297851:ios:4c20162f9108b896155f1e',
    messagingSenderId: '19391297851',
    projectId: 'random-chat-app-b',
    storageBucket: 'random-chat-app-b.appspot.com',
    iosBundleId: 'com.example.randamChatAppb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA14Hwgst4p_7_3TjW2eJN2BbwhZZI2_2Q',
    appId: '1:19391297851:web:91f1d454f686b00a155f1e',
    messagingSenderId: '19391297851',
    projectId: 'random-chat-app-b',
    authDomain: 'random-chat-app-b.firebaseapp.com',
    storageBucket: 'random-chat-app-b.appspot.com',
    measurementId: 'G-N3VLLZP4NW',
  );
}
